plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
    id 'idea'
}

version '0'

repositories {
    maven {
        name "Mod Menu Maven Repo"
        url "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation "com.terraformersmc:modmenu:18.0.0-beta.1"
    implementation project(path: ":Source")
}

tasks.withType(JavaCompile) {
    source(project(":Source").sourceSets.main.allSource)
}